#!/usr/bin/env zsh

_del() {
  local tmp="/tmp"
  for file in "$@"; do
    [[ -e "$file" || -L "$file" ]] \
      && mv -f --backup=t "$file" "$tmp" &> /dev/null \
      || rm -rf "$file" &> /dev/null
    
  done
}

_del "$@"
