#!/usr/bin/env zsh

_del() {
  local tmp="/tmp"
  for file in "$@"; do
    [[ -e "$file" || -L "$file" ]] || continue 
    [[ "$(dirname $file)" == "$tmp" ]] && rm -rf "$file" && continue
    mv -f --backup=t "$file" "$tmp"
  done
}

_del "$@"
