#!/usr/bin/env zsh

_preview() {
  local file="$1"
  autoload -Uz has exe
  if [[ -d "$file" ]] || [[ -h "$file" ]]; then
    local cmd="$(exe exa lsd ls)"
    [[ -x "$cmd" ]] && $cmd -lh --color=always "$file"
  elif [[ -f "$file" ]]; then
    local conf="${XDG_CONFIG_HOME:-"$HOME/.config"}"
    local scope="${RANGER_CFG:-"$conf/ranger"}/scope.sh"
    if [[ -f "$scope" ]]; then
      : "${file##*/}"
      : "${_##*.}"
      local cache="$(mktemp -u Scope.sh.XXXXXXXX.$_)"
      local columns="$COLUMNS"
      [[ -t 0 ]] || ((columns=columns/2-10)) 
      bash "$scope" "$file" "$columns" "$LINES" "$cache" "False"
      return 0
    fi
    info="$(file "$file")"
    if [[ "$info" == *text* ]]; then
      if has bat; then
        bat --color=always "$file"
      else
        head -n 50 "$file"
      fi
    else
      echo "$info"
    fi
  fi
}

_preview "$@"
