#!/data/data/com.termux/files/usr/bin/zsh
pip3 list -o --user | sed '1,2d' | awk '{print $1}' | xargs pip3 install --user -U
pip3 list -o | sed '1,2d' | awk '{print $1}' | xargs sudo -H pip3 install -U
