#!/usr/bin/env zsh

export PATH="$HOME/.local/bin:$PATH"

_v() {
  local opt=()
  local query=()
  local editor=(${EDITOR:-vim})
  while [[ -n "$1" ]]; do
    case $1 in
      -h|-H|h|H)
        opt=($opt --hidden)
        ;;
      -l|-L|l|L)
        opt=($opt --type symlink)
        ;;
      -s|-S|s|S)
        editor=(sudo $editor)
        ;;
      -*)
        ;;
      *)
        query=($query $1)
        ;;
    esac
    shift
  done
  [[ -e "$query" ]] && $editor "$query" && return
  file=$(fd --color=always --type file $opt .+ . ~ /etc /var | \
    fzf -1 +m --ansi --cycle --inline-info --height 50% --border \
    --layout=reverse --preview="bat --color=always {}" --query "$query") && \
    $editor "$file" || $editor "$query"
}

_v "$@"
