#!/data/data/com.termux/files/usr/bin/bash

_del() {
  local tmp="/tmp"
  if [[ ! -w "$tmp" ]] && [[ -w "$TMPDIR" ]]; then
    tmp="$TMPDIR"
  fi
  for file in "$@"; do
    [[ -e "$file" || -L "$file" ]] \
      && mv -f --backup=t "$file" "$tmp" && continue
    rm -rf "$file"
  done
}

_del "$@"
