#! /usr/bin/env bash
# shellcheck disable=SC2139

: "/etc/profile" && [[ -f "$_" ]] && source "$_"
: "$HOME/.bashrc" && [[ -f "$_" ]] && source "$_"

bind "\C-f":beginning-of-line

if command -v vim &> /dev/null; then
  : "$SSHRCD/vimrc" && [[ -f "$_" ]] \
    && alias v="command vim -u '$_'" \
    && export EDITOR="v"
  alias vd="vimdiff"
  alias e="vim"
fi

: "$SSHRCD/common.sh" && [[ -f "$_" ]] && source "$_"
: "$SSHRCD/del" && [[ -x "$_" ]] && alias del="$_"

bind '"2": "2>&1 "'
bind '"e": "2>/dev/null "'
bind '"f": "| tail -f "'
bind '"h": "| head -q "'
bind '"l": "| less -r "'
bind '"n": ">/dev/null "'
bind '"t": "| tail "'

alias md="mkdir -p"

alias -- -="cd -"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ssl="ss -ltnp"

if command -v ag &> /dev/null; then
  alias agc="ag --color"
  bind '"g": "| ag --color "'
elif command -v rg &> /dev/null; then
  alias rg="rg --smart-case"
  alias rgc="\\rg --smart-case --color=always"
  bind '"g": "| \\rg --smart-case --color=always "'
else
  alias ag="grep -Ein"
  alias agc="grep -Ein --color=always"
  bind '"g": "| grep -Ein --color=always "'
fi

take() {
  mkdir -p "$1" && cd "$1" || return
}

