set number
set relativenumber
set autoindent
set smartindent
set showcmd
set showmode
set tabstop=2
set shiftwidth=2
set scrolloff=4
set softtabstop=2
set backspace=indent,eol,start
set showmatch
set hlsearch
set incsearch
set smartcase
set ruler
set expandtab
set encoding=utf-8
set timeoutlen=500
set nocompatible
set autoread
set autowrite
set hidden
syntax on
filetype plugin indent on

" for i in range(97,122)
  " let c = nr2char(i)
  " execute "map \e".c." <M-".c.">"
  " execute "map! \e".c." <M-".c.">"
" endfor

inoremap <s-cr> <esc>o
inoremap <c-a> <c-o>^
inoremap <c-f> <c-o>^
inoremap <c-e> <c-o>$
inoremap <c-k> <c-o>D
inoremap <c-[> <esc>
inoremap <c-]> <esc>
inoremap  <c-w>
inoremap [3;5~ <c-o>dw

cnoremap w!! w !sudo tee > /dev/null %
nnoremap <space>q :w !sudo tee % > /dev/null<cr>L:qa<cr>
nnoremap <space>z :w !sudo tee % > /dev/null<cr>

nnoremap K :grep! -F '<c-r><c-w>' .<cr>:cwindow<cr>
vnoremap K y:grep! -F '<c-r>0' .<cr>:cwindow<cr>

if executable('ag')
  set grepprg=ag\ --vimgrep\ --smart-case\ 2>/dev/null
elseif executable('rg')
  set grepprg=rg\ --vimgrep\ --smart-case\ 2>/dev/null
else
  nnoremap K :grep! -s -r -F '<c-r><c-w>' .<cr>:cwindow<cr>
  vnoremap K y:grep! -s -r -F '<c-r>0' .<cr>:cwindow<cr>
endif

nnoremap [0 :cfirst<cr>
nnoremap ]0 :clast<cr>
nnoremap [o :copen<cr>
nnoremap ]o :cclose<cr>
nnoremap [c :cprevious<cr>
nnoremap ]c :cnext<cr>
nnoremap [9 :lfirst<cr>
nnoremap ]9 :llast<cr>
nnoremap [q :lopen<cr>
nnoremap ]q :lclose<cr>
nnoremap [l :lprevious<cr>
nnoremap ]l :lnext<cr>

noremap Y y$
noremap <F2> :redraw<cr>
noremap <F8> :let @/ = ""<cr>
nnoremap <leader><cr> :nohlsearch<cr>
nnoremap <space><cr> :nohlsearch<cr>

nnoremap gz `[v`]
vnoremap < <gv
vnoremap > >gv
vnoremap p pgvy
vnoremap v ^$h
vnoremap * y/\V<c-r>0<cr>
vnoremap # y?\V<c-r>0<cr>

vnoremap x "_x
vnoremap s "_s

noremap <c-j> :bnext<cr>
noremap <c-k> :bprevious<cr>
nnoremap <leader>d :bdelete<cr>
nnoremap <space>d :bdelete<cr>
noremap <Up> gk
noremap <Down> gj

nnoremap <leader>sw "_yiw:s/\(\%#\w\+\)\(\W\+\)\(\w\+\)/\3\2\1/<cr><c-o>
