set number
set autoindent
set showcmd
set tabstop=2
set shiftwidth=2
set scrolloff=4
set softtabstop=2
set backspace=indent,eol,start
set showmatch
set hlsearch
set incsearch
set smartcase
set ruler
set expandtab
set encoding=utf-8
filetype plugin indent on

set nocompatible
syntax on

inoremap <s-cr> <esc>o
inoremap <c-y> <c-o>cc
inoremap <c-a> <c-o>^
inoremap <c-e> <c-o>$
inoremap <c-[> <esc>
inoremap <c-]> <esc>

noremap Y y$
noremap <F8> :let @/ = ""<cr>
noremap <space><cr> :let @/ = ""<cr>

vnoremap < <gv
vnoremap > >gv
vnoremap p pgvy

noremap <c-l> :bnext<cr>
noremap <c-h> :bprevious<cr>
nnoremap <leader>d :bdelete<cr>
nnoremap <space>d :bdelete<cr>
noremap <Up> gk
noremap <Down> gj

nnoremap <leader>r viwpgvy
nnoremap <space>r viwpgvy
nnoremap <leader>sw "_yiw:s/\(\%#\w\+\)\(\W\+\)\(\w\+\)/\3\2\1/<cr><c-o>
